controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

controllers_api:
    resource: ../src/Controller/api
    type: attribute
    prefix: /api
